theme: Architect
title: Wenaknan
description: Wenaknan adalah sebuah web app yang menyediakan jasa  pemesanan makanan dan minuman, dilengkapi dengan sebuah sistem rekomendasi  berbasis kecerdasan buatan yang bisa memberikan rekomendasi menu yang lebih  terpersonalisasi terhadap pengguna.
